# Generated by Django 4.2 on 2023-04-08 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_file', models.FileField(upload_to='driving_license')),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_driving_license', to='vehicle.vehicle')),
            ],
        ),
    ]
