# Generated by Django 4.2 on 2023-04-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclebrand',
            name='brand_name',
            field=models.CharField(max_length=30),
        ),
    ]
