# Generated by Django 4.2 on 2023-04-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivinglicense',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='drivinglicense',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
