# Generated by Django 4.2 on 2023-04-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_drivinglicense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivinglicense',
            old_name='Vehicle',
            new_name='vehicle',
        ),
    ]
