# Generated by Django 4.2 on 2023-04-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_drivinglicense_unique_driving_license_per_vehicle'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='drivinglicense',
            name='unique_driving_license_per_vehicle',
        ),
    ]
