# Generated by Django 4.2 on 2023-04-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_remove_drivinglicense_unique_driving_license_per_vehicle'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='drivinglicense',
            constraint=models.UniqueConstraint(fields=('vehicle',), name='unique_driving_license_per_vehicle'),
        ),
    ]
